module.exports = {
    'extends': 'stylelint-config-standard',
    'rules': {
        'indentation': 4,
        'string-quotes': 'single',
        'no-duplicate-selectors': true,
        'color-hex-case': 'lower',
        'color-hex-length': 'short',
        'color-named': 'never',
        'selector-no-qualifying-type': true,
        'selector-combinator-space-after': 'always',
        'selector-attribute-quotes': 'always',
        'selector-attribute-operator-space-before': 'never',
        'selector-attribute-operator-space-after': 'never',
        'selector-attribute-brackets-space-inside': 'never',
        'declaration-block-trailing-semicolon': 'always',
        'declaration-empty-line-before': 'never',
        'declaration-no-important': true,
        'declaration-colon-space-before': 'never',
        'declaration-colon-space-after': 'always',
        'number-leading-zero': 'never',
        'function-url-quotes': 'always',
        'font-weight-notation': 'numeric',
        'font-family-name-quotes': 'always-where-recommended',
        'comment-whitespace-inside': 'always',
        'comment-empty-line-before': 'always',
        'selector-pseudo-element-colon-notation': 'single',
        'selector-pseudo-class-parentheses-space-inside': 'never',
        'media-feature-range-operator-space-before': 'always',
        'media-feature-range-operator-space-after': 'always',
        'media-feature-parentheses-space-inside': 'never',
        'media-feature-colon-space-before': 'never',
        'media-feature-colon-space-after': 'always',
        'media-feature-name-no-vendor-prefix': true,
        'at-rule-no-vendor-prefix': true,
        'property-no-vendor-prefix': true,
        'selector-no-vendor-prefix': true,
        'value-no-vendor-prefix': true,
        'max-nesting-depth': 3,
        'selector-max-compound-selectors': 3,
        'max-empty-lines': 2,
        'selector-max-id': 0,
        'ignoreAtRules': ['extend', 'import', 'mixin']
    }
}
